## Ejemplo básico de como se procesa un choque de oferta en una economía

In [3]:
import numpy as np

# ==========================================
# 1. DEFINICIÓN DE LA MATRIZ A (Coeficientes Técnicos)
# ==========================================
# UNIDADES: "Dólares de insumo por cada 1 dólar de producción total".
# Es adimensional ($/$), representa una proporción o receta.
#
# LECTURA:
# - Las COLUMNAS representan al sector que COMPRA (el que produce).
# - Las FILAS representan al sector que VENDE (el insumo).
#
# Ejemplo detallado de la Matriz A abajo:
# Columna 0 (Agricultura): Para producir $1 de comida, gasta:
#   - $0.10 en semillas (compra a Agricultura)
#   - $0.30 en tractores (compra a Industria)
#   - $0.10 en logística (compra a Servicios)

A = np.array([
    # Ag    Ind   Serv  <-- COMPRADOR (Output)
    [0.10, 0.20, 0.05], # Fila 0: Venta de Agricultura
    [0.30, 0.40, 0.10], # Fila 1: Venta de Industria
    [0.10, 0.10, 0.30]  # Fila 2: Venta de Servicios
])

# ==========================================
# 2. DEFINICIÓN DEL VECTOR d (Demanda Final)
# ==========================================
# UNIDADES: Millones de dólares ($).
# ORIGEN: Esto viene de datos externos (lo que el gobierno,
# las familias o el extranjero quieren comprar este año).
#
# Escenario:
# - La gente quiere comprar 100M en comida.
# - La gente quiere comprar 50M en productos industriales.
# - La gente quiere comprar 200M en servicios.

d = np.array([100, 50, 200])

# ==========================================
# 3. CÁLCULO DE LA INVERSA DE LEONTIEF
# ==========================================
# Fórmula: x = (I - A)^-1 * d

# a) Crear la Matriz Identidad (I) del mismo tamaño que A (3x3)
n = A.shape[0]
I = np.eye(n)

# b) Calcular (I - A)
# Esto representa cuánto valor "sobra" para demanda final después
# de cubrir los insumos internos.
I_minus_A = I - A

# c) Calcular la Inversa de Leontief: (I - A)^-1
# Esta matriz nos dice el "efecto multiplicador" total.
Leontief_Inverse = np.linalg.inv(I_minus_A)

print("--- Matriz Inversa de Leontief (Multiplicadores) ---")
print(np.round(Leontief_Inverse, 3))
print("\nInterpetación: El valor [1,0] indica cuánto debe producir Industria")
print("extra por cada dólar extra demandado a Agricultura.\n")

# ==========================================
# 4. RESOLUCIÓN DEL VECTOR x (Producción Total)
# ==========================================
# Multiplicamos la Inversa por la Demanda.
# x = L * d

x = np.dot(Leontief_Inverse, d)

# ==========================================
# 5. RESULTADOS
# ==========================================
print("--- Producción Total Necesaria (Vector x) ---")
sectores = ["Agricultura", "Industria  ", "Servicios  "]

for i in range(len(x)):
    print(f"Sector {sectores[i]}: ${x[i]:.2f} Millones")

print("\n--- Conclusión ---")
print(f"Para vender ${sum(d)}M a los consumidores finales,")
print(f"la economía debe mover un total interno de ${sum(x):.2f}M")

--- Matriz Inversa de Leontief (Multiplicadores) ---
[[1.279 0.452 0.156]
 [0.686 1.95  0.328]
 [0.281 0.343 1.498]]

Interpetación: El valor [1,0] indica cuánto debe producir Industria
extra por cada dólar extra demandado a Agricultura.

--- Producción Total Necesaria (Vector x) ---
Sector Agricultura: $181.75 Millones
Sector Industria  : $231.67 Millones
Sector Servicios  : $344.77 Millones

--- Conclusión ---
Para vender $350M a los consumidores finales,
la economía debe mover un total interno de $758.19M
